on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'utils.R'
      - 'renv.lock'
      - 'ectd_readme/README.qmd'

name: Publish ECTD bundle

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render ADRG PDF (custom)
        env:
          QUARTO_PRINT_STACK: true
        run: |
          quarto render adrg/adrg-quarto-pdf.qmd --to pdf
        shell: bash

      - name: Render ECTD README (custom)
        env:
          QUARTO_PRINT_STACK: true
        run: |
          quarto render ectd_readme/README.qmd --to gfm

      - name: Render cover letter (custom)
        env:
          QUARTO PRINT STACK: true
        run: |
          quarto render cover-letter/cover-letter.qmd


      - name: Compile pkglite file (custom)
        run: |
          source("utils.R"); create_app_pkglite_bundle(); create_env_pkglite_bundle()
        shell: Rscript {0}

      - name: Set up object storage s3cmd cli tool
        uses: s3-actions/s3cmd@v1.6.1
        with:
          provider: linode
          region: 'us-east-1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Check out ECTD bundle destination repo
        uses: actions/checkout@v4
        with:
          repository: RConsortium/submissions-pilot4-webR-to-fda
          path: ./submissions-pilot4-webR-to-fda
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Create ECTD bundle
        run: bash ./.github/scripts/create-ectd-bundle.sh

      - name: Push ECTD bundle
        run: bash ./.github/scripts/push-ectd-bundle.sh
      
      - name: Publish ADRG PDF to object storage
        run: |
          s3cmd put adrg/adrg-quarto-pdf.pdf --mime-type 'application/pdf' --acl-public s3://rsubmission-draft/pilot4-webR-adrg.pdf

