on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'adrg/_adrg.qmd'

name: Quarto Publish ADRG

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render ADRG (custom)
        if: ${{ false }}
        env: 
          QUARTO_PRINT_STACK: true
        run: |
          quarto render adrg/adrg-quarto.qmd --to html
        shell: bash

      - name: Publish to GH pages (custom)
        if: ${{ false }}
        env:
          QUARTO_PRINT_STACK: true
        run: |
          quarto publish gh-pages adrg/adrg-quarto.qmd --no-render --no-browser --no-prompt

      - name: Publish HTML version to GH pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: adrg/adrg-quarto-html.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
