# NOT WORKING: GH Pages does not render app correctly
# TODO: Experiment with netlify in a GH action (low priority)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'

name: Publish App to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Compile application (custom)
        run: |
          source("utils.R"); build_app()
        shell: Rscript {0}
      
      # Use an Action deploy to push the artifact onto Netlify
      - name: Deploy to Net lify
        id: deployment
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: _site
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"