on:
  workflow_dispatch:
    inputs:
      debug-enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
  push:
    branches:
      - main

name: Publish ECTD bundle

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Compile ECTD Bundle (custom)
        run: |
          source("utils.R"); create_ectd_bundle()
        shell: Rscript {0}

      - name: Check out ECTD bundle destination repo
        uses: actions/checkout@v4
        with:
          repository: RConsortium/submissions-pilot4-webR-to-fda
          path: ./submissions-pilot4-webR-to-fda
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ false }}

      - name: Copy ECTD bundle
        run: bash ./.github/scripts/copy-ectd-bundle.sh
        env:
          DESTINATION_DIR: submissions-pilot4-webR-to-fda/m5/datasets/rconsortiumpilot4/analysis/adam/programs

      - name: Push ECTD bundle
        run: bash ./.github/scripts/push-ectd-bundle.sh
